name: Daily Scheduled Playwright Tests

on:
  schedule:
    - cron: '0 6 * * *' # runs daily at 06:00 UTC (08:00 CEST)
  workflow_dispatch: # manual trigger

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug - Print Node.js version
        run: node -v # Check Node.js version
       
      - name: Debug - Print npm version
        run: npm -v # Check npm version

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          npm run build # if you have a build step, for debugging

      - name: Debug - Check installed node modules
        run: |
          echo "Listing node_modules..."
          ls -la node_modules # List contents of node_modules to verify

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          echo "Running Playwright tests..."
          npx playwright test

      - name: Upload Playwright report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/**